# Generated by Django 2.0.7 on 2018-07-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_info',
            new_name='info',
        ),
    ]
