# Generated by Django 2.0.7 on 2018-07-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='dust',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='light',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='voltage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
