# Generated by Django 2.0.7 on 2018-08-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0003_auto_20180802_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_number',
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
