# Generated by Django 2.0.7 on 2018-08-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0003_auto_20180730_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='user_notes',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
