# Generated by Django 2.0.7 on 2018-08-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0004_device_user_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_number',
        ),
        migrations.AddField(
            model_name='data',
            name='dust',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='light',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='voltage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='info',
            field=models.CharField(max_length=100),
        ),
    ]
