# Generated by Django 2.0.7 on 2018-08-03 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0005_auto_20180802_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user_notes',
            field=models.CharField(blank=True, default=datetime.datetime(2018, 8, 3, 20, 55, 10, 277403), max_length=200),
            preserve_default=False,
        ),
    ]
