# Generated by Django 2.0.7 on 2018-08-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0006_auto_20180803_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='datapoints',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='device',
            name='preference',
            field=models.BooleanField(default=False),
        ),
    ]
