# Generated by Django 2.0.7 on 2018-08-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0008_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='device_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
