# Generated by Django 2.0.7 on 2018-08-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0009_email_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='dust_set_point',
            field=models.IntegerField(default=51),
        ),
        migrations.AddField(
            model_name='email',
            name='dust_trigger',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='email',
            name='dust_warnings',
            field=models.IntegerField(default=0),
        ),
    ]
