# Generated by Django 2.0.7 on 2018-08-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0010_auto_20180811_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='dust_warnings',
        ),
        migrations.AddField(
            model_name='device',
            name='dust_warnings',
            field=models.IntegerField(default=0),
        ),
    ]
