# Generated by Django 2.0.7 on 2018-08-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0011_auto_20180811_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='dust_set_point',
        ),
        migrations.AddField(
            model_name='device',
            name='dust_set_point',
            field=models.IntegerField(default=51),
        ),
    ]
