# Generated by Django 2.0.7 on 2018-08-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0012_auto_20180811_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='email',
            name='dust_trigger',
        ),
        migrations.AddField(
            model_name='device',
            name='dust_trigger',
            field=models.IntegerField(default=2),
        ),
    ]
