# Generated by Django 2.0.7 on 2018-08-12 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0014_auto_20180811_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alarm',
            name='time_ack',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 12, 10, 1, 3, 80375)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alarm',
            name='time_over',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 12, 10, 1, 23, 20053)),
            preserve_default=False,
        ),
    ]
