# Generated by Django 2.0.7 on 2018-08-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0016_auto_20180812_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='device_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
