# Generated by Django 2.0.7 on 2018-08-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0017_alarm_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='device_id',
            field=models.IntegerField(null=True),
        ),
    ]
