# Generated by Django 2.0.7 on 2018-08-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0018_auto_20180812_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='alarm',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='humd_treshold',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='device',
            name='humd_trigger',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='device',
            name='humd_warnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='light_treshold',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='device',
            name='light_warnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='temp_treshold',
            field=models.IntegerField(default=26),
        ),
        migrations.AddField(
            model_name='device',
            name='temp_trigger',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='device',
            name='temp_warnings',
            field=models.IntegerField(default=0),
        ),
    ]
