# Generated by Django 2.0.7 on 2018-08-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0020_device_light_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dust_warning',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='device',
            name='humd_warning',
            field=models.IntegerField(default=55),
        ),
        migrations.AddField(
            model_name='device',
            name='temp_warning',
            field=models.IntegerField(default=26),
        ),
        migrations.AlterField(
            model_name='device',
            name='temp_treshold',
            field=models.IntegerField(default=30),
        ),
    ]
