# Generated by Django 2.0.7 on 2018-08-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0021_auto_20180814_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='light_warning',
            field=models.IntegerField(default=10000),
        ),
    ]
