# Generated by Django 2.0.7 on 2018-08-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0022_device_light_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='dust_set_point',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='dust_warning',
            field=models.IntegerField(default=8),
        ),
    ]
