# Generated by Django 2.0.7 on 2018-08-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0023_auto_20180816_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='volt_alarm',
            field=models.FloatField(default=3.4),
        ),
        migrations.AddField(
            model_name='device',
            name='volt_warning',
            field=models.FloatField(default=3.6),
        ),
        migrations.AlterField(
            model_name='data',
            name='voltage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
