# Generated by Django 2.0.7 on 2018-08-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0024_auto_20180817_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='voltage',
            field=models.FloatField(default=0),
        ),
    ]
