# Generated by Django 2.0.7 on 2018-08-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0025_auto_20180817_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='voltage',
            field=models.FloatField(default=100.0),
        ),
    ]
